AgendaTarefas/Models/Contexto.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaTarefas.Models
{
    public class Contexto :DbContext
    {

        public DbSet<Tarefa> Tarefas { get; set; }

        public Contexto(DbContextOptions<Contexto> opcoes):base(opcoes)
        {

        }
    }
}

AgendaTarefas/Models/DatasViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaTarefas.Models
{
    public class DatasViewModel
    {
        public string Datas { get; set; }

        public string Identificadores { get; set; }
    }
}

AgendaTarefas/Models/ErrorViewModel.cs
using System;

namespace AgendaTarefas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgendaTarefas/Models/Tarefa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaTarefas.Models
{
    public class Tarefa
    {

        public int TarefaId { get; set; }

        [Required(ErrorMessage ="{0} é obrigatório")]
        [StringLength(50, ErrorMessage ="Use menos carateres")]
        public string Nome { get; set; }

        public string Data { get; set; }

        [Required(ErrorMessage = "{0} é obrigatório")]
        [DataType(DataType.Time)]
        public string Horario { get; set; }
    }
}

AgendaTarefas/Controllers/TarefasController.cs
using AgendaTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaTarefas.Controllers
{
    public class TarefasController : Controller
    {
        private readonly Contexto _contexto;

        public TarefasController(Contexto contexto)
        {
            _contexto = contexto;
        }
        public IActionResult Index()
        {
            return View(PegarDatas());
        }

        private List<DatasViewModel> PegarDatas()
        {
            DateTime dataAtual = DateTime.Now;
            DateTime dataLimite = DateTime.Now.AddDays(10);
            int qtdDias = 0;
            DatasViewModel data;
            List<DatasViewModel> listaDatas = new List<DatasViewModel>();

            while(dataAtual < dataLimite)
            {
                data = new DatasViewModel();
                data.Datas = dataAtual.ToShortDateString();
                data.Identificadores = "collapse" + dataAtual.ToShortDateString().Replace("/", "");
                listaDatas.Add(data);
                qtdDias = qtdDias + 1;
                dataAtual = DateTime.Now.AddDays(qtdDias);
            }
            return listaDatas;
        }
        [HttpGet]
        public IActionResult CriarTarefa(string dataTarefa)
        {
            Tarefa tarefa = new Tarefa
            {
                Data = dataTarefa
            };

            return View(tarefa);
        }

        [HttpPost]
        public async Task<IActionResult> CriarTarefa(Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                _contexto.Tarefas.Add(tarefa);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(tarefa);
        }

        [HttpGet]
        public async Task<IActionResult> AtualizarTarefa(int tarefaId)
        {
            Tarefa tarefa = await _contexto.Tarefas.FindAsync(tarefaId);

            if (tarefa == null)
                return NotFound();

            return View(tarefa);
        }
        [HttpPost]
        public async Task<IActionResult> AtualizarTarefa(Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                _contexto.Update(tarefa);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(tarefa);
        }

        [HttpPost]
        public async Task<JsonResult> ExcluirTarefa(int tarefaId)
        {
            Tarefa tarefa = await _contexto.Tarefas.FindAsync(tarefaId);
            _contexto.Tarefas.Remove(tarefa);
            await _contexto.SaveChangesAsync();
            return Json(true);  
        }
    }
}

AgendaTarefas/ViewComponents/ListaTarefasViewComponent.cs
using AgendaTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaTarefas.ViewComponents
{
    public class ListaTarefasViewComponent : ViewComponent
    {
        private readonly Contexto _contexto;

        public ListaTarefasViewComponent(Contexto contexto)
        {
            _contexto = contexto;
        }

        public async Task<IViewComponentResult> InvokeAsync(string data)
        {
            return View(await _contexto.Tarefas
                .OrderBy(t => t.Horario).Where(t => t.Data == data).ToListAsync());
        }
    }
}

AgendaTarefas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AgendaTarefas/Views/Shared/Components/ListaTarefas/Default.cshtml
@model IEnumerable<AgendaTarefas.Models.Tarefa>

@{ 
    Layout = null;
}

<div class="border border-left shadow rounded rounded-lg p-4" >
    @if(Model.Count() > 0)
    {
        <ul class="list-group">
            @foreach(var item in Model)
            {
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-2">
                            <span class="badge badge-info">@Html.DisplayFor(modelItem => item.Horario)</span>
                        </div>

                        <div class="col-6">
                            @Html.DisplayFor(modelItem => item.Nome)
                        </div>

                        <div class="col-4">
                            <a asp-action="AtualizarTarefa" asp-route-tarefaId="@item.TarefaId" class="btn btn-sm btn-outline-primary rounded-circle"><i class="fa fa-pencil-square-o"></i></a>
                            <a href="#" class="btn btn-sm btn-outline-danger rounded-circle" onclick="ConfirmarExclusao(@item.TarefaId, '@item.Nome')"><i class="fa fa-times-circle"></i></a>
                        </div>
                    </div>
                </li>
            }
        </ul>
    }
    else
    {
        <p class="alert alert-warning">Sem tarefas ainda</p>
    }
</div>

AgendaTarefas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgendaTarefas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AgendaTarefas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AgendaTarefas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AgendaTarefas/Views/Tarefas/AtualizarTarefa.cshtml
@model AgendaTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Atualizar tarefa na data " + Model.Data;
}



<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <text class="card-header">Atualizar tarefa na data @Model.Data</text>
                <form asp-action="AtualizarTarefa">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="TarefaId" />
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control" />
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>

                        <input asp-for="Data" type="hidden" />

                        <div class="form-group">
                            <label asp-for="Horario" class="control-label"></label>
                            <input asp-for="Horario" class="form-control" />
                            <span asp-validation-for="Horario" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="form-group">
                            <input type="submit" value="Atualizar" class="btn btn-sm btn-outline-primary" /> &emsp;
                            <a asp-action="Index" class="btn btn-sm btn-link">Voltar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

AgendaTarefas/Views/Tarefas/CriarTarefa.cshtml
@model AgendaTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Nova tarefa na data " + Model.Data;
}



<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <text class="card-header">Nova tarefa na data @Model.Data</text>
                <form asp-action="CriarTarefa">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control" />
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                        
                            <input asp-for="Data" type="hidden" />
                            
                   
                        <div class="form-group">
                            <label asp-for="Horario" class="control-label"></label>
                            <input asp-for="Horario" class="form-control" />
                            <span asp-validation-for="Horario" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="form-group">
                            <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" /> &emsp;
                            <a asp-action="Index" class="btn btn-sm btn-link">Voltar</a>
                        </div>
                    </div>                  
                </form>
            </div>
        </div>
    </div>
</div>

AgendaTarefas/Views/Tarefas/Index.cshtml
@model IEnumerable<AgendaTarefas.Models.DatasViewModel>

@{
    ViewData["Title"] = "Tarefas Cadastradas";
}

@foreach (var item in Model)
{
    <div class="accordion" id="painelTarefas">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-10">
                        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#@item.Identificadores">
                            @item.Datas
                        </button>
                    </div>
                    <div class="col-2">
                        <a asp-action="CriarTarefa" asp-route-dataTarefa="@item.Datas" class="btn btn-sm btn-outline-dark">Nova Tarefa</a>
                    </div>
                </div>
            </div>
            <div id="@item.Identificadores" class="collapse show" data-parent="#painelTarefas">
                <div class="card-body">
                    @await Component.InvokeAsync("ListaTarefas", item.Datas)
                </div>
            </div>
        </div>
    </div>
}


<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirmação de Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Prosseguir com a exclusão da tarefa <text class="nomeTarefa"></text> ? </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary btnFechar" data-dismiss="modal">Não</button>
                <button type="button" class="btn btn-outline-danger btnExcluir">Sim</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
    function ConfirmarExclusao(tarefaId, nomeTarefa) {
        $(".nomeTarefa").text(nomeTarefa);
        $(".modal").modal();
        $(".btnExcluir").on('click', function () {
            $.ajax({
                url: 'Tarefas/ExcluirTarefa',
                method: 'POST',
                data: { tarefaId: tarefaId },
                success: function (data) {
                    $(".modal").modal('hide');
                    location.reload(true);
                }
            });
        });
        $('.btnFechar').on('click', function () {
            tarefaId = null;
            nomeTarefa = null;
            $(".modal").modal('hide');
        });
    }
    </script>
}